openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib auth'
  description: auth api specifications

tags:
  - name: auth

paths:
  /signout:
    post:
      operationId: signout
      tags:
        - auth
      summary: signout of viron
      description: Vironからログアウトする
      responses:
        '204':
          description: OK

  /email/signin:
    post:
      operationId: signinEmail
      tags:
        - auth
      summary: signin to viron with email/password
      description: Emailアドレスとパスワードを使ってVironにサインインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninEmailPayload'
      responses:
        '204':
          description: No Content

  /oidc/authorization:
    get:
      operationId: oidcAuthorization
      tags:
        - auth
      summary: redirect to oidc idp authorization
      description: OIDCの idp 認証画面へリダイレクトするための情報、ステータスを返却する
      parameters:
        - $ref: '#/components/parameters/RedirectUriQueryParam'
        - $ref: '#/components/parameters/ClientIdQueryParam'
      responses:
        '200':
          description: authorization url を返却し、アプリケーション側にリダイレクトを促す
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationRedirect'
        '301':
          description: Redirect to OIDC Authorization URL.
      x-authconfig-default-parameters:
        redirectUri: '${oidcRedirectURI}'

  /oidc/callback:
    post:
      operationId: oidcCallback
      tags:
        - auth
      summary: callback from oidc
      description: OIDC認可後のコールバックURL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcCallbackPayload'
      responses:
        '204':
          description: No Content.
      x-authconfig-default-requestBody:
        redirectUri: '${oidcRedirectURI}'

  /oauth2/google/authorization:
    get:
      operationId: oauth2GoogleAuthorization
      tags:
        - auth
      summary: redirect to google oauth
      description: Google の OAuth 認証画面へリダイレクトするための情報、ステータスを返却する
      parameters:
        - $ref: '#/components/parameters/RedirectUriQueryParam'
        - $ref: '#/components/parameters/ClientIdQueryParam'
      responses:
        '200':
          description: authorization url を返却し、アプリケーション側にリダイレクトを促す
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationRedirect'
        '301':
          description: Redirect to Google OAuth URL.
      x-authconfig-default-parameters:
        redirectUri: '${oauthRedirectURI}'

  /oauth2/google/callback:
    post:
      operationId: oauth2GoogleCallback
      tags:
        - auth
      summary: callback from google oauth
      description: Google認可後のコールバックURL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuth2GoogleCallbackPayload'
      responses:
        '204':
          description: No Content.
      x-authconfig-default-requestBody:
        redirectUri: '${oauthRedirectURI}'

components:
  parameters:
    RedirectUriQueryParam:
      name: redirectUri
      in: query
      schema:
        type: string
        format: uri
      required: true
    CodeQueryParam:
      name: code
      in: query
      schema:
        type: string
      required: true
    ClientIdQueryParam:
      name: clientId
      in: query
      schema:
        type: string
      required: true

  schemas:
    SigninEmailPayload:
      type: object
      properties:
        email:
          description: Eメールアドレス
          type: string
          format: email
        password:
          description: パスワード
          type: string
          format: password
          pattern: "^(?=.*?[a-zA-Z])(?=.*?\\d)[a-zA-Z\\d!?#$%&@*+/-_<=>]{8,}"
      required:
        - email
        - password

    OAuth2GoogleCallbackPayload:
      type: object
      properties:
        code:
          description: Googleが発行した認可コード
          type: string
        state:
          description: CSRF対策用のステートパラメータ
          type: string
        redirectUri:
          description: GoogleOAuth2コールバックURI
          type: string
        clientId:
          description: GoogleOAuth2クライアントID
          type: string
      required:
        - code
        - state
        - redirectUri
        - clientId

    OidcCallbackPayload:
      type: object
      properties:
        code:
          description: OIDC Idpが発行した認可コード
          type: string
        state:
          description: CSRF対策用のステートパラメータ
          type: string
        redirectUri:
          description: OIDCコールバックURI
          type: string
        clientId:
          description: OIDCクライアントID
          type: string
      required:
        - code
        - state
        - redirectUri
        - clientId

    AuthenticationRedirect:
      type: object
      properties:
        authorizationUrl:
          type: string
          format: uri
