openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib auth'
  description: auth api specifications

tags:
  - name: auth

paths:
  /signout:
    post:
      operationId: signout
      tags:
        - auth
      summary: signout of viron
      description: Vironからログアウトする
      responses:
        204:
          description: OK

  /email/signin:
    post:
      operationId: signinEmail
      tags:
        - auth
      summary: signin to viron with email/password
      description: Emailアドレスとパスワードを使ってVironにサインインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninEmailPayload'
      responses:
        204:
          description: No Content

  /oauth2/google/authorization:
    get:
      operationId: oauth2GoogleAuthorization
      tags:
        - auth
      summary: redirect to google oauth
      description: GoogleのOAuth認可画面へリダイレクトする
      parameters:
        - $ref: '#/components/parameters/EndpointIdQueryParam'
        - $ref: '#/components/parameters/RedirectUriQueryParam'
      responses:
        301:
          description: Redirect to Google OAuth URL.

  /oauth2/google/callback:
    post:
      operationId: oauth2GoogleCallback
      tags:
        - auth
      summary: callback from google oauth
      description: Google認可後のコールバックURL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuth2GoogleCallbackPayload'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuth2GoogleCallback'

components:
  parameters:
    EndpointIdQueryParam:
      name: endpointId
      in: query
      schema:
        type: string
      required: true

    RedirectUriQueryParam:
      name: redirectUri
      in: query
      schema:
        type: string
        format: uri
      required: true

  schemas:
    SigninEmailPayload:
      type: object
      properties:
        email:
          description: Eメールアドレス
          type: string
          format: email
        password:
          description: パスワード
          type: string
          format: password
          pattern: "^(?=.*?[a-zA-Z])(?=.*?\\d)[a-zA-Z\\d!?#$%&@*+/-_<=>]{8,}"
      required:
        - email
        - password

    OAuth2GoogleCallback:
      type: object
      properties:
        endpointId:
          description: Vironが発行したエンドポイントID
          type: string
      required:
        - endpointId

    OAuth2GoogleCallbackPayload:
      type: object
      properties:
        code:
          description: Googleが発行した認可コード
          type: string
        state:
          description: CSRF対策用のステートパラメータ
          type: string
      required:
        - code
        - state
