[mysql]
  dbname    = "viron_example"
  host      = "localhost"
  port      = 3306
  user      = "root"
  pass      = "password"
  sslmode   = "false"
  whitelist = ["adminusers", "auditlogs", "revokedtokens", "adminuserssotokens"]