
version: '3.8'

services:

  example_golang:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000
    environment:
      - MODE=mysql
    env_file:
      - .env
    volumes:
      - $PWD/go.mod:/example/golang/go.mod
      - $PWD/go.sum:/example/golang/go.sum
      - $PWD/cmd:/example/golang/cmd
      - $PWD/pkg:/example/golang/pkg
      - $PWD/../../packages/golang:/packages/golang
      - $PWD/../../packages/golang-linter:/packages/golang-linter
    command: go run cmd/main.go

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $PWD/data/mongo/db:/data/db
    env_file: mongo.env
    networks:
      default:
        aliases:
          - viron.example.golang
