
version: '3.8'

services:

  example:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:8000
    environment:
      - MODE=mysql
    env_file:
      - .env
    volumes:
      - $PWD/go.mod:/example/golang/go.mod
      - $PWD/go.sum:/example/golang/go.sum
      - $PWD/cmd:/example/golang/cmd
      - $PWD/pkg:/example/golang/pkg
      - $PWD/../../packages/golang:/packages/golang
      - $PWD/../../packages/golang-linter:/packages/golang-linter
    command: go run cmd/main.go

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - $PWD/data/mysql/db:/var/lib/mysql
    env_file: mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      default:
        aliases:
          - viron.example.golang
