import { isSSR } from '$utils/index';

export const ON = {
  BACKGROUND: 'background',
  SURFACE: 'surface',
  PRIMARY: 'primary',
  COMPLEMENTARY: 'complementary',
} as const;
export type On = typeof ON[keyof typeof ON];

export const URL = {
  DOCUMENTATION: 'https://discovery.viron.app/docs/',
  BLOG: 'https://discovery.viron.app/blog/',
  RELEASE_NOTES: 'https://viron.app/TODO/release_notes/',
  HELP: 'https://viron.app/TODO/help/',
  GITHUB: 'https://github.com/cam-inc/viron/',
  TWITTER: 'https://twitter.com/TODO',
} as const;
export type Url = typeof URL[keyof typeof URL];

export const ENVIRONMENTAL_VARIABLE = {
  AUTOCOMPLETE_VALUE: '${autocompleteValue}',
  OAUTH_REDIRECT_URI: '${oauthRedirectURI}',
} as const;
export type EnvironmentalVariable =
  typeof ENVIRONMENTAL_VARIABLE[keyof typeof ENVIRONMENTAL_VARIABLE];

export const OAUTH_REDIRECT_URI = (function () {
  if (isSSR) {
    return '';
  }
  return `${window.location.origin}/oauthredirect`;
})();

export const STATUS_CODE = {
  CONTINUE: 100,
  SWITCHING_PROTOCOL: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,
  MULTIPLE_CHOICE: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 413,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_ONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVER_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;
export type StatusCode = typeof STATUS_CODE[keyof typeof STATUS_CODE];
