// Package components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package components

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// 作成日時
type VironCreatedAt time.Time

// VironPager defines model for VironPager.
type VironPager struct {
	CurrentPage int `json:"currentPage"`
	MaxPage     int `json:"maxPage"`
}

// 更新日時
type VironUpdatedAt time.Time

// VironEmailQueryParam defines model for VironEmailQueryParam.
type VironEmailQueryParam string

// VironIdPathParam defines model for VironIdPathParam.
type VironIdPathParam string

// VironIdQueryParam defines model for VironIdQueryParam.
type VironIdQueryParam string

// VironPagerPageQueryParam defines model for VironPagerPageQueryParam.
type VironPagerPageQueryParam int

// VironPagerSizeQueryParam defines model for VironPagerSizeQueryParam.
type VironPagerSizeQueryParam int

// VironRoleIdQueryParam defines model for VironRoleIdQueryParam.
type VironRoleIdQueryParam string

// VironSortQueryParam defines model for VironSortQueryParam.
type VironSortQueryParam []string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RUO28TQRD+K9aIAsRyONBdAwhRpDNE0CCQ1ndz9qDbR2bnojjBDRUlFQhBS09By79B",
	"9zvQrJEfwY6d5qSbb/Z7zD4uoQouBo9eEpSXEC1bh4Kc/14RB//MWWqfd8izkYJaJw8lnGoJDHjrEEpA",
	"bQMDqZqis9ols6hAEiY/gfncLPiO65GV6SZXtDJdUVENBhhPO2KsoRTu8CDe/SYz816mkZ0g62eTsMZU",
	"MUWhoMyKD3znxsiD0AxaSgJmq2i0E9wmS15wgnxF94QurtVVfI9goovDBF+EFg8ZG+e+Q0Z3EliudR9Y",
	"BiliRQ1VVotrWfA8tqFGKBvbJtyRLbBsGCFB9+/oiiDrkrfF3UflbZuq9yp+5xaYq3YNOPLHi5VHS9Qy",
	"25mCSWatFprALmdbyK3uxFNGK1g/kf8T/vn9vf/4qf/yo//6AUymsAIl1FbwnpDDbW5W25+TcIjIQpgF",
	"q44ZvSi6bS8NOHu+C5yv36PXy06zQfpmaSiM32ElS0MvY70rZf/tV//5541SqhnyTcg+SfKAH5+pzv2W",
	"xoO1d8jAGXJaCA2LYXGkjkJEbyNBCQ+LYfEATH40EpS+a9v53wAAAP//VGXS08gEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
