version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Login to ECR.
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker pull $REPOSITORY_URI:latest || true
      - docker login $DOCKER_PROXY_HOST -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - >
        docker build
        --cache-from $REPOSITORY_URI:latest
        --build-arg DOCKER_PROXY_HOST=$DOCKER_PROXY_HOST
        -t $IMAGE_REPO_NAME:latest
        -f ./example/nodejs/Dockerfile ./example/nodejs
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:$COMMIT_ID
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo push step...
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_ID
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - codepipeline/demo-deployspec.yml
  name: viron-demo-artifact
  discard-paths: no
