version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo Install packages...
      - npm ci --no-progress
      - echo Building linter...
      - cd $CODEBUILD_SRC_DIR/packages/linter
      - npm run build

  build:
    commands:
      - echo Building app...
      - cd $CODEBUILD_SRC_DIR/packages/app
      - npm run build:prefix


artifacts:
  files:
    - codepipeline/snapshot-app-deployspec.yml
    - packages/app/package.json
    - packages/app/public/**/*
  name: viron-snapshot-app-artifact
  discard-paths: no
