version: '3.8'

services:
  example:
    build:
      context: './'
      dockerfile: ./Dockerfile.example
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229 # node-inspector
    environment:
      - MODE=mongo
    env_file:
      - ./.env
    # volumes:
    #   - ./package.json:/viron/package.json
    #   - ./src:/viron/src
    #   - ./cert:/viron/cert
    #   - ../../packages/nodejs:/viron/packages/nodejs
    #   - ../../packages/linter:/viron/packages/linter
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
    env_file: mongo.env
    networks:
      default:
        aliases:
          - viron.example.nodejs
