version: '2'
services:

  demo:
    # 240*1024*1024 = 251658240 Byte = 240 MB
    mem_limit: 251658240
    build: .
    working_dir: "/demo"
    depends_on:
      - mysql
    ports:
      - 3000:3000
      - 53000:53000
    environment:
      - SERVICE_ENV=local
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    volumes:
      - $PWD/package.json:/demo/package.json
      - $PWD/shared:/demo/shared
      - $PWD/config:/demo/config
      - $PWD/app.js:/demo/app.js
      - $PWD/controllers:/demo/controllers
      - $PWD/fittings:/demo/fittings
      - $PWD/swagger:/demo/swagger
      - $PWD/public:/demo/public
      - $PWD/test:/demo/test
      - $PWD/.env:/demo/.env
      - $PWD/mysql.env:/demo/mysql.env
      - $PWD/wait-for-it.sh:/demo/wait-for-it.sh
    command: bash -c
      "
          chmod +x /demo/wait-for-it.sh && \
          /demo/wait-for-it.sh viron.dev:3306 --timeout=60 --strict -- \
          npm run inspect
      "
    #command: tail -f /var/log/bootstrap.log

  mysql:
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    image: mysql/mysql-server:8.0
    # platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - $PWD/docker/mysql/data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "user", "-ppassword"]
     interval: 10s
     timeout: 5s
     retries: 5
    networks:
      default:
        aliases:
          - viron.dev
