openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib auditlogs'
  description: auditlogs api specifications
  x-pages:
    - id: vironAuditLog
      group: 管理画面/管理
      title: Viron 監査ログ
      description: このVironサーバの監査ログを閲覧できます
      contents:
        - operationId: listVironAuditlogs
          resourceId: vironAuditLog
          type: table
          query:
            - userId
            - requestUri
          sort:
            - requestMethod
            - requestUri
            - sourceIp
            - userId
            - statusCode
            - createdAt

tags:
  - name: vironAuditLog

paths:
  /viron/auditlogs:
    get:
      operationId: listVironAuditlogs
      tags:
        - vironAuditLog
      summary: list audit logs
      description: 監査ログ一覧
      parameters:
        - $ref: '#/components/parameters/VironUserIdQueryParam'
        - $ref: '#/components/parameters/VironRequestUriQueryParam'
        - $ref: '#/components/parameters/VironRequestMethodQueryParam'
        - $ref: '#/components/parameters/VironSourceIpQueryParam'
        - $ref: '#/components/parameters/VironStatusCodeQueryParam'
        - $ref: './components.yaml#/components/parameters/VironPagerSizeQueryParam'
        - $ref: './components.yaml#/components/parameters/VironPagerPageQueryParam'
        - $ref: './components.yaml#/components/parameters/VironSortQueryParam'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VironAuditLogListWithPager'
      security:
        - jwt: []

components:
  parameters:
    VironUserIdQueryParam:
      name: userId
      in: query
      schema:
        type: string
      required: false

    VironRequestUriQueryParam:
      name: requestUri
      in: query
      schema:
        type: string
      required: false

    VironRequestMethodQueryParam:
      name: requestMethod
      in: query
      schema:
        type: string
      required: false

    VironSourceIpQueryParam:
      name: sourceIp
      in: query
      schema:
        type: string
      required: false

    VironStatusCodeQueryParam:
      name: statusCode
      in: query
      schema:
        type: integer
        format: int32
      required: false

  schemas:
    VironAuditLogListWithPager:
      allOf:
        - $ref: './components.yaml#/components/schemas/VironPager'
        - type: object
          properties:
            list:
              $ref: '#/components/schemas/VironAuditLogList'
          required:
            - list

    VironAuditLogList:
      type: array
      items:
        $ref: '#/components/schemas/VironAuditLog'

    VironAuditLog:
      type: object
      properties:
        requestMethod:
          description: リクエストメソッド
          type: string
        requestUri:
          description: リクエストURI
          type: string
        sourceIp:
          description: ソースIP
          type: string
        userId:
          description: ユーザーID
          type: string
        requestBody:
          description: リクエストボディ
          type: string
        statusCode:
          description: ステータスコード
          type: integer
        createdAt:
          description: 日時
          type: string
          format: date-time
