name: NodeJs Viron/lib Package CI

on:
  # for debug
  pull_request:
    types: [opened]
  push:
    branches:
      - develop
    paths:
      - "packages/nodejs/**"
      - "package.json"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: |
          echo "Installing packages..."
          npm install --no-progress --legacy-peer-deps
          npm run build -w packages/linter
          cd packages/nodejs
          npm cache verify
      - name: Set NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Build and Publish
        run: |
          echo "Building..."
          npm run build
          echo "Publishing..."
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
