name: Publish NPM Package - Viron/lib

on:
  push:
    branches:
      - develop
    paths:
      - "packages/nodejs/**"

permissions:
  id-token: write  # Required for OIDC
  contents: read
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"
      - name: Update npm
        run: npm install -g npm@11.6.2
      - name: Install dependencies and Build
        run: |
          echo "Installing packages..."
          npm ci
          npm run build -w packages/linter
          npm run build -w packages/nodejs
      - name: Publish with OIDC
        run: |
          echo "Publishing..."
          npm publish -w packages/nodejs
