// API "example-go": Application Resource Href Factories
//
// Code generated by goagen v1.1.0-dirty, DO NOT EDIT.
//
// Command:
// $ goagen
// --design=github.com/cam-inc/example-go/design
// --out=$(GOPATH)/src/github.com/cam-inc/example-go
// --version=v1.1.0-dirty

package app

import (
	"fmt"
	"strings"
)

// DmcHref returns the resource href.
func DmcHref() string {
	return "/dmc"
}

// OverviewHref returns the resource href.
func OverviewHref() string {
	return "/overview"
}

// UserHref returns the resource href.
func UserHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/user/%v", paramid)
}
